"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup

APP = ['__main__.py']
DATA_FILES = ['exe', 'exe/sudoku.png']
OPTIONS = {'argv_emulation': False, 'includes':['tkinter', 'os','copy','time','random','errno','signal','functools'],'packages': ['PIL', 'gui','play_board','solver']}

setup(
    app=APP,
    data_files=DATA_FILES,
    package_dir={'':'exe'},
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
